[package]
name = "print-prep"
version = "0.1.0"
authors = ["m-lange <martin_lange_@gmx.net>"]
edition = "2018"

[[bin]]
name = "pprep"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
